name: build-commit

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - "changelog.md"
      - ".editorconfig"
      - "mod/src/**/resources/assets/*/lang/**"
      - "media/**"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
      - "changelog.md"
      - ".editorconfig"
      - "mod/src/**/resources/assets/*/lang/**"
      - "media/**"
  workflow_dispatch:

concurrency:
  group: build-commit-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-mod:
    runs-on: ubuntu-latest
    name: ${{ matrix.version }} / ${{ matrix.loader }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "26.1"
            loader: fabric
          - version: "26.1"
            loader: neoforge
          - version: "26.3"
            loader: fabric

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build and test
        run: ./gradlew :mod:${{ matrix.version }}-${{ matrix.loader }}:build --stacktrace
      - name: Store test reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: test-reports-${{ matrix.version }}-${{ matrix.loader }}
          if-no-files-found: warn
          path: |
            mod/versions/${{ matrix.version }}-${{ matrix.loader }}/build/reports/
            mod/versions/${{ matrix.version }}-${{ matrix.loader }}/build/test-results/
      - name: Store build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: better-boat-movement-${{ matrix.version }}-${{ matrix.loader }}
          path: mod/versions/${{ matrix.version }}-${{ matrix.loader }}/build/libs/*.jar

  build-paper:
    runs-on: ubuntu-latest
    name: Paper

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build and test
        run: ./gradlew :paper:build --stacktrace
      - name: Store test reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: test-reports-paper
          if-no-files-found: warn
          path: |
            paper/build/reports/
            paper/build/test-results/
      - name: Store build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: better-boat-movement-paper
          path: paper/build/libs/*.jar
