name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode GPG Key
        run: |
          mkdir -p ~/.gradle/
          echo "${{ secrets.GPG_SECRET_KEY }}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
      - name: Release with Gradle
        uses: Wandalen/wretry.action@master
        with:
          command: ./gradlew releaseAllVersions --stacktrace -Psigning.keyId=${{ secrets.GPG_SECRET_KEY_ID }} -Psigning.password='${{ secrets.GPG_SECRET_KEY_PASSWORD }}' -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          NYON_USERNAME: ${{ secrets.NYON_USERNAME }}
          NYON_PASSWORD: ${{ secrets.NYON_PASSWORD }}
