name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Release with Gradle
        run: ./gradlew releaseAllVersions
